# docker-compose.yml
version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"

      SERVER_NAME: "The place to chill. ^-^"
      MOTD: "The only love you need. ❤️"

      DIFFICULTY: "hard"

      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: 6G
        
      #VANILLATWEAKS_SHARECODE: izhLiC

      # uncomment this to import a saved game. (put your savegame directory in the saves-to-import directory)
      WORLD: "/worlds/world"

    volumes:
      - ./minecraft-data:/data
      - ./saves-to-import:/worlds:ro	
      #- ./datapacks:/data/world/datapacks

#mkdir minecraft-data
#mkdir saves-to-import
#curl -fsSL https://get.docker.com -o get-docker.sh
#sh get-docker.sh
